import { 
  SiteLocation, 
  ExtinguisherAsset,
  HoodSystemAsset,
  GreaseTrapAsset,
  ServiceRequest,
  ContractorMessage,
  DeficiencyQuote
} from '@compliance-saas/backend-core';

export const CLIENT_PROFILE = {
  id: 'user-elena',
  customerId: 'cust-grand-horizon',
  companyName: 'Grand Horizon Hospitality Group',
  name: 'Elena Rostova',
  role: 'VP of Facilities & Asset Management',
  email: 'elena@grandhorizon.com',
  phone: '(555) 234-5678',
  avatarUrl: 'https://images.unsplash.com/photo-1573496359142-b8d87734a5a2?w=150&auto=format&fit=crop&q=80',
};

export const CONTRACTOR_CONTACT = {
  name: 'Apex Fire & Environmental Compliance Group',
  dispatchPhone: '(555) 998-1122',
  dispatchEmail: 'dispatch@apexcompliance.com',
  licenseNumbers: 'NFPA 10 Lic #IL-8842 • NFPA 96 Lic #IL-9941 • EPA FOG Hauler #IL-7781',
};

export const CLIENT_SITES: SiteLocation[] = [
  {
    id: 'site-grand-horizon-resort',
    orgId: 'org-apex',
    customerId: 'cust-grand-horizon',
    siteName: 'Grand Horizon Resort & Convention Center',
    address: {
      street: '777 Lakeshore Boulevard',
      city: 'Chicago',
      state: 'IL',
      zip: '60601',
    },
    siteContact: {
      name: 'Carlos Mendez (Chief Engineer)',
      email: 'cmendez@grandhorizon.com',
      phone: '(555) 234-5680',
    },
    expectedExtinguisherCount: 18,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'site-grand-horizon-downtown',
    orgId: 'org-apex',
    customerId: 'cust-grand-horizon',
    siteName: 'Grand Horizon Downtown Hotel & Suites',
    address: {
      street: '320 N Michigan Avenue',
      city: 'Chicago',
      state: 'IL',
      zip: '60601',
    },
    siteContact: {
      name: 'Elena Rostova',
      email: 'elena@grandhorizon.com',
      phone: '(555) 234-5678',
    },
    expectedExtinguisherCount: 12,
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const CLIENT_EXTINGUISHERS: ExtinguisherAsset[] = [
  {
    id: 'ext-01',
    orgId: 'org-apex',
    customerId: 'cust-grand-horizon',
    siteId: 'site-grand-horizon-resort',
    qrCode: 'EXT-1001',
    serialNumber: 'SN-AMX-9941',
    barcode: '071234567890',
    manufacturer: 'Amerex',
    model: 'B402',
    type: 'ABC_Dry_Chemical',
    capacityLbs: 10,
    mfgYear: 2022,
    floor: 'Floor 1',
    roomOrArea: 'Main Lobby Reception Desk Alcove',
    lastAnnualInspectionAt: '2026-08-18T00:00:00Z',
    status: 'pass',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'ext-02',
    orgId: 'org-apex',
    customerId: 'cust-grand-horizon',
    siteId: 'site-grand-horizon-resort',
    qrCode: 'EXT-1002',
    serialNumber: 'SN-KID-8832',
    manufacturer: 'Kidde',
    model: 'Pro-Line K',
    type: 'Class_K_Wet_Chemical',
    capacityLbs: 6,
    mfgYear: 2021,
    floor: 'Floor 1',
    roomOrArea: 'Commercial Banquet Kitchen Fryer Line',
    lastAnnualInspectionAt: '2026-08-18T00:00:00Z',
    status: 'pass',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'ext-03',
    orgId: 'org-apex',
    customerId: 'cust-grand-horizon',
    siteId: 'site-grand-horizon-resort',
    qrCode: 'EXT-1003',
    serialNumber: 'SN-BAD-7719',
    manufacturer: 'Badger',
    model: 'B15-CO2',
    type: 'CO2',
    capacityLbs: 15,
    mfgYear: 2018,
    floor: 'Basement',
    roomOrArea: 'Main Electrical Switchgear Vault Room B-12',
    lastAnnualInspectionAt: '2026-08-18T00:00:00Z',
    status: 'service_required',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const CLIENT_HOODS: HoodSystemAsset[] = [
  {
    id: 'hood-01',
    orgId: 'org-apex',
    customerId: 'cust-grand-horizon',
    siteId: 'site-grand-horizon-resort',
    systemName: 'Main Banquet Kitchen 24ft Cook Line Canopy',
    locationDescription: 'Main Banquet Kitchen 1st Floor',
    hoodLengthFeet: 24,
    ductType: 'welded_steel',
    fanType: 'upblast_roof',
    fanHingesInstalled: true,
    accessPanelsCount: 4,
    cookingVolume: 'high',
    lastCleanedAt: '2026-05-15T00:00:00Z',
    nextCleaningDueAt: '2026-08-15T00:00:00Z',
    serviceIntervalMonths: 3,
    lastCondition: 'cleaned_to_bare_metal',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'hood-02',
    orgId: 'org-apex',
    customerId: 'cust-grand-horizon',
    siteId: 'site-grand-horizon-resort',
    systemName: 'Pastry & Baking Oven Line Exhaust',
    locationDescription: 'Pastry Kitchen 1st Floor',
    hoodLengthFeet: 12,
    ductType: 'stainless',
    fanType: 'upblast_roof',
    fanHingesInstalled: true,
    accessPanelsCount: 2,
    cookingVolume: 'low',
    lastCleanedAt: '2026-02-10T00:00:00Z',
    nextCleaningDueAt: '2027-02-10T00:00:00Z',
    serviceIntervalMonths: 12,
    lastCondition: 'cleaned_to_bare_metal',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const CLIENT_GREASE_TRAPS: GreaseTrapAsset[] = [
  {
    id: 'trap-01',
    orgId: 'org-apex',
    customerId: 'cust-grand-horizon',
    siteId: 'site-grand-horizon-resort',
    internalId: 'GT-OUTDOOR-1500',
    trapType: 'gravity',
    capacityGallons: 1500,
    flowRateGpm: 100,
    locationDescription: 'North Loading Dock Sub-Grade Asphalt Vault',
    serviceIntervalDays: 90,
    lastPumpedAt: '2026-05-10T00:00:00Z',
    nextPumpDueAt: '2026-08-10T00:00:00Z',
    lastCondition: 'heavy_fog',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
  {
    id: 'trap-02',
    orgId: 'org-apex',
    customerId: 'cust-grand-horizon',
    siteId: 'site-grand-horizon-resort',
    internalId: 'GT-POTWASH-50',
    trapType: 'indoor_interceptor',
    capacityGallons: 50,
    flowRateGpm: 25,
    locationDescription: 'Banquet Potwash Sink Under-Counter',
    serviceIntervalDays: 30,
    lastPumpedAt: '2026-07-28T00:00:00Z',
    nextPumpDueAt: '2026-08-28T00:00:00Z',
    lastCondition: 'good',
    createdAt: new Date().toISOString(),
    updatedAt: new Date().toISOString(),
  },
];

export const CLIENT_DEFICIENCY_QUOTES: DeficiencyQuote[] = [
  {
    id: 'quote-01',
    orgId: 'org-apex',
    customerId: 'cust-grand-horizon',
    siteId: 'site-grand-horizon-resort',
    serviceVertical: 'extinguisher',
    deficiencyId: 'def-ext-03',
    assetCode: 'EXT-1003',
    assetLocation: 'Basement Electrical Room B-12',
    issueDescription: 'Pressure gauge below operational green zone. Unit requires 6-year internal inspection, hydrostatic test, and recharge.',
    recommendedAction: 'Perform 15lb CO2 Hydrostatic Test, replace valve stem O-ring, recharge, and apply new 2026 certification collar ring.',
    severity: 'major',
    estimatedCost: 85.00,
    status: 'pending',
    createdAt: '2026-08-18T10:00:00Z',
  },
  {
    id: 'quote-02',
    orgId: 'org-apex',
    customerId: 'cust-grand-horizon',
    siteId: 'site-grand-horizon-resort',
    serviceVertical: 'hood_cleaning',
    deficiencyId: 'def-hood-access',
    assetCode: 'HOOD-01',
    assetLocation: 'Main Banquet Kitchen 4th Floor Shaft',
    issueDescription: 'Inaccessible horizontal duct elbow lacking fire-rated access panel (NFPA 96 Section 7.4.1 compliance deficiency).',
    recommendedAction: 'Fabricate and install 20"x20" UL 1978 Listed fire-rated high-temperature duct access door with silicone gasket.',
    severity: 'critical',
    estimatedCost: 450.00,
    status: 'pending',
    createdAt: '2026-08-15T14:30:00Z',
  },
];

export const CLIENT_MESSAGES: ContractorMessage[] = [
  {
    id: 'msg-01',
    orgId: 'org-apex',
    customerId: 'cust-grand-horizon',
    senderId: 'tech-brandon',
    senderName: 'Brandon Scott (Field Supervisor)',
    senderRole: 'technician',
    content: 'Hi Elena, we finished the annual fire extinguisher walk at the Lakeshore Resort today. 17 units passed 100%. Unit EXT-1003 in Electrical Room B-12 was depressurized and we created a quote for the hydro test.',
    createdAt: '2026-08-18T11:20:00Z',
  },
  {
    id: 'msg-02',
    orgId: 'org-apex',
    customerId: 'cust-grand-horizon',
    senderId: 'user-elena',
    senderName: 'Elena Rostova',
    senderRole: 'client',
    content: 'Thank you Brandon. I just saw the quote in the portal. Can you also make sure the kitchen hood cleaning crew comes in after 11 PM on Monday when the banquet service closes?',
    createdAt: '2026-08-18T11:45:00Z',
  },
  {
    id: 'msg-03',
    orgId: 'org-apex',
    customerId: 'cust-grand-horizon',
    senderId: 'dispatcher-sarah',
    senderName: 'Sarah Jenkins (Dispatch)',
    senderRole: 'contractor',
    content: 'Noted Elena! We have your kitchen hood cleaning crew scheduled for Monday, August 24 at 11:15 PM. The crew will have the roof exhaust fan hinged and protected.',
    createdAt: '2026-08-18T12:05:00Z',
  },
];

export const CLIENT_REQUESTS: ServiceRequest[] = [
  {
    id: 'req-01',
    orgId: 'org-apex',
    customerId: 'cust-grand-horizon',
    siteId: 'site-grand-horizon-resort',
    serviceVertical: 'grease_trap',
    requestedBy: {
      name: 'Carlos Mendez',
      email: 'cmendez@grandhorizon.com',
      phone: '(555) 234-5680',
    },
    preferredDate: '2026-08-25',
    priority: 'routine',
    description: 'Quarterly pumping required for outdoor 1500 gallon grease interceptor before Labor Day weekend banquet volume.',
    status: 'scheduled',
    createdAt: '2026-08-19T09:00:00Z',
    updatedAt: '2026-08-19T10:30:00Z',
  },
];
